import turtle
tom = turtle.Turtle()
tom.shape("turtle")
tom.color("blue")
tom.speed(1)
tom.forward(100)
tom.left(135)
tom.forward(72)
print(tom.pos() )
tom.left(90)
tom.forward(72)
tom.left(45)
tom.speed(1)
tom.forward(100)
tom.left(90)

tom.forward(100)
tom.write("My House", font=("Arial", 10, "normal"), align="right")
tom.left(90)
tom.forward(100)

print(tom.pos() )
tom.penup()
tom.goto((100,100))
tom.pendown()
tom.circle(50)
turtle.done() 